process {
    executor = 'slurm'
    clusterOptions = '--qos=normal'
    queue = 'amilan'
    module = 'miniforge'
    cpus = 4
    memory = { 3840.MB * task.cpus }
    time = '2h'
    errorStrategy = 'retry'
    maxRetries = 2
    maxForks = 4

    withName: 'FLYE' {
        cpus = 8
        time = '2h'
        maxForks = 2
    }

    withName: 'MEDAKA' {
        cpus = 8
        time = '4h'
        maxForks = 2
    }
}
