process {
    executor = 'slurm'
    clusterOptions = '--qos=normal'
    queue = 'amilan'
    module = 'miniforge'
    cpus = 6
    memory = { 3840.MB * task.cpus }
    time = '2h'
    errorStrategy = 'retry'
    maxRetries = 1
    maxForks = 6

    withName: 'FLYE' {
        cpus = 8
        time = '2h'
        maxForks = 4
    }

    withName: 'MEDAKA' {
        cpus = 8
        time = '4h'
        maxForks = 4
    }
    withName: 'PROKKA' {
        cpus = 8
        time = '4h'
        maxForks = 4
    }
}
executor {
    queueSize = 20
    submitRateLimit = '5/1min'
}
