process {
    executor = 'local'
    conda.enabled = true
    apptainer.enabled = true

    def availCpus = Runtime.getRuntime().availableProcessors()
    cpus = availCpus
    memory = { 3840.MB * availCpus }
}

